#!/bin/bash

MakeSByBPlot --SIGSAMPLEFILE=signal_list_TTDoublet_1L.txt --BKGSAMPLEFILE=bkg_list_1L.txt --OUTNAME=TTDoublet --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=FALSE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SIGSAMPLEFILE=signal_list_TTSinglet_1L.txt --BKGSAMPLEFILE=bkg_list_1L.txt --OUTNAME=TTSinglet --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=FALSE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SIGSAMPLEFILE=signal_list_HtHt_1L.txt --BKGSAMPLEFILE=bkg_list_1L.txt --OUTNAME=HtHt --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=FALSE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SIGSAMPLEFILE=signal_list_HtZt_1L.txt --BKGSAMPLEFILE=bkg_list_1L.txt --OUTNAME=HtZt --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=FALSE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SIGSAMPLEFILE=signal_list_HtWb_1L.txt --BKGSAMPLEFILE=bkg_list_1L.txt --OUTNAME=HtWb --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=FALSE --VARBIN=1000 --DOLATEXTABLE=TRUE
