#!/bin/bash

MakeSByBPlot --SIGSAMPLEFILE=signal_list_HtHt_0L.txt --BKGSAMPLEFILE=bkg_list_0L.txt --OUTNAME=HtHt --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=TRUE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SIGSAMPLEFILE=signal_list_ZtZt_0L.txt --BKGSAMPLEFILE=bkg_list_0L.txt --OUTNAME=ZtZt --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=TRUE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SIGSAMPLEFILE=signal_list_HtZt_0L.txt --BKGSAMPLEFILE=bkg_list_0L.txt --OUTNAME=HtZt --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=TRUE --VARBIN=1000 --DOLATEXTABLE=TRUE
