#!/bin/bash

MakeSByBPlot --SAMPLEFILE=signal_list_HtHt_0L.txt --OUTNAME=HtHt --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=TRUE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SAMPLEFILE=signal_list_ZtZt_0L.txt --OUTNAME=ZtZt --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=TRUE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SAMPLEFILE=signal_list_TTSinglet_0L.txt --OUTNAME=Singlet --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=TRUE --VARBIN=1000 --DOLATEXTABLE=TRUE

MakeSByBPlot --SAMPLEFILE=signal_list_TTDoublet_0L.txt --OUTNAME=Doublet --VARIABLE=meff --DOOLDREGIONS=FALSE --DO0LEPTON=TRUE --VARBIN=1000 --DOLATEXTABLE=TRUE
