// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : CrossValidation::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.16/00       [397312]
Creator        : tfarooque
Date           : Wed Apr 27 18:58:39 2022
Host           : Linux aibuild16-005.cern.ch 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/at3/scratch2/farooque/FerMerge/VLQAnalysisFramework/run/CrossValidation
Training events: 100691
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
EncapsulatedMethodName: "MLP" []
EncapsulatedMethodTypeName: "MLP" []
NumFolds: "5" [Number of folds to generate]
OutputEnsembling: "None" [Combines output from contained methods. If None, no combination is performed. (default None)]
SplitExpr: "int([event_number])%int([numFolds])" [The expression used to assign events to folds]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 26
meff                          meff                          meff                          meff                          GeV                               'D'    [1000.17388916,7032.98681641]
leadingdEta_RCjets            leadingdEta_RC                leadingdEta_RC                leadingdEta_RC                                                  'D'    [8.69482755661e-06,1.94405603409]
leadingdR_RCjets              leadingdR_RC                  leadingdR_RC                  leadingdR_RC                                                    'D'    [0.0345592722297,3.59982872009]
leadingdR_RCTTMassRCTTMass    leadingdR_RCTTM               leadingdR_RCTTM               leadingdR_RCTTM                                                 'D'    [0.0629397556186,4.95888948441]
dEtamin_RCTTMassRCTTMass      dEtamin_RCTTM                 dEtamin_RCTTM                 dEtamin_RCTTM                                                   'F'    [1.26957893372e-05,3.89710259438]
dRmin_RCTTMassRCTTMass        dRmin_RCTTM                   dRmin_RCTTM                   dRmin_RCTTM                                                     'F'    [0.0345592722297,4.95888948441]
dPhiaverage_RCjets            dPhiaverage_RC                dPhiaverage_RC                dPhiaverage_RC                                                  'D'    [0.151427194476,2.09439516068]
dRaverage_RCjets              dRaverage_RC                  dRaverage_RC                  dRaverage_RC                                                    'D'    [1.32892823219,3.84989714622]
Alt$(RCjets_pt[1],0)          RCjet1_pt                     RCjet1_pt                     RCjet1_pt                                                       'D'    [300.01663208,2491.31591797]
Alt$(RCjets_pt[2],0)          RCjet2_pt                     RCjet2_pt                     RCjet2_pt                                                       'D'    [200.001037598,1597.57641602]
Alt$(RCMTop_jets_pt[0],0)     RCMTop_jet0_pt                RCMTop_jet0_pt                RCMTop_jet0_pt                                                  'D'    [0,2781.40600586]
Alt$(RCMHiggs_jets_pt[0],0)   RCMHiggs_jet0_pt              RCMHiggs_jet0_pt              RCMHiggs_jet0_pt                                                'D'    [0,2569.89868164]
Alt$(RCMHiggs_jets_pt[1],0)   RCMHiggs_jet1_pt              RCMHiggs_jet1_pt              RCMHiggs_jet1_pt                                                'D'    [0,1823.0880127]
Alt$(RCMV_jets_eta[0],-10)    RCMV_jet0_eta                 RCMV_jet0_eta                 RCMV_jet0_eta                                                   'D'    [-10,1.99997079372]
Alt$(RCMHiggs_jets_consts_n[0],0) RCMHiggs_jet0_nconsts             RCMHiggs_jet0_nconsts             RCMHiggs_jet0_nconsts                                                   'I'    [0,2]
Alt$(RCMHiggs_jets_bconsts_n[0],0) RCMHiggs_jet0_nbconsts             RCMHiggs_jet0_nbconsts             RCMHiggs_jet0_nbconsts                                                    'I'    [0,4]
Alt$(RCMV_jets_bconsts_n[0],0) RCMV_jet0_nbconsts             RCMV_jet0_nbconsts             RCMV_jet0_nbconsts                                                'I'    [0,5]
leptop_pt                     leptop_pt                     leptop_pt                     leptop_pt                                                       'D'    [0,2674.48291016]
mtw                           mtw                           mtw                           mtw                                                             'D'    [0.00321702472866,1453.86035156]
residualMET_Pt                residualMET_Pt                residualMET_Pt                residualMET_Pt                                                  'D'    [0,1710.64428711]
met                           met                           met                           met                                                             'D'    [20.0051307678,1793.10070801]
mT_bmin                       mT_bmin                       mT_bmin                       mT_bmin                                                         'D'    [0.000345200009178,1011.98236084]
trkbjets_n                    trkbjets_n                    trkbjets_n                    trkbjets_n                                                      'I'    [3,9]
Alt$(m_vlq_rcttmass_drmax[0],0) mvlq_rcttm1                     mvlq_rcttm1                     mvlq_rcttm1                                                         'D'    [-1001.48852539,5968.77685547]
Alt$(m_vlq_rcttmass_drmax[1],0) mvlq_rcttm2                     mvlq_rcttm2                     mvlq_rcttm2                                                         'D'    [-2553.39477539,4775.85205078]
Alt$(m_vlq_rcjets_drmax[1],0) mvlq_rc2                      mvlq_rc2                      mvlq_rc2                                                        'D'    [-2553.39477539,5761.8046875]
NSpec 53
event_number                  event_number                  event_number                  event_number                                                    'F'    [1,38956852]
leadingdEta_RCTTMassRCTTMass  leadingdEta_RCTTM             leadingdEta_RCTTM             leadingdEta_RCTTM                                               'F'    [1.26957893372e-05,3.89710259438]
leadingdPhi_RCjets            leadingdPhi_RC                leadingdPhi_RC                leadingdPhi_RC                                                  'F'    [1.54972076416e-05,2.09145021439]
leadingdPhi_RCTTMassRCTTMass  leadingdPhi_RCTTM             leadingdPhi_RCTTM             leadingdPhi_RCTTM                                               'F'    [0.00068187713623,3.1415784359]
dEtamin_RCjets                dEtamin_RC                    dEtamin_RC                    dEtamin_RC                                                      'F'    [8.69482755661e-06,1.94405603409]
dPhimin_RCjets                dPhimin_RC                    dPhimin_RC                    dPhimin_RC                                                      'F'    [1.54972076416e-05,2.09145021439]
dPhimin_RCTTMassRCTTMass      dPhimin_RCTTM                 dPhimin_RCTTM                 dPhimin_RCTTM                                                   'F'    [7.97510147095e-05,3.1415784359]
dRmin_RCjets                  dRmin_RC                      dRmin_RC                      dRmin_RC                                                        'F'    [0.0345592722297,3.59982872009]
dEtaaverage_RCjets            dEtaaverage_RC                dEtaaverage_RC                dEtaaverage_RC                                                  'F'    [0.00236537051387,2.65048646927]
dEtaaverage_RCTTMassRCTTMass  dEtaaverage_RCTTM             dEtaaverage_RCTTM             dEtaaverage_RCTTM                                               'F'    [1.26957893372e-05,3.89710259438]
dPhiaverage_RCTTMassRCTTMass  dPhiaverage_RCTTM             dPhiaverage_RCTTM             dPhiaverage_RCTTM                                               'F'    [0.00068187713623,3.1415784359]
dRaverage_RCTTMassRCTTMass    dRaverage_RCTTM               dRaverage_RCTTM               dRaverage_RCTTM                                                 'F'    [0.234225064516,4.95888948441]
Alt$(RCjets_pt[0],0)          RCjet0_pt                     RCjet0_pt                     RCjet0_pt                                                       'F'    [301.034881592,2781.40600586]
Alt$(RCMTop_jets_pt[1],0)     RCMTop_jet1_pt                RCMTop_jet1_pt                RCMTop_jet1_pt                                                  'F'    [0,2491.31591797]
Alt$(RCMTop_jets_pt[2],0)     RCMTop_jet2_pt                RCMTop_jet2_pt                RCMTop_jet2_pt                                                  'F'    [0,993.495361328]
Alt$(RCMHiggs_jets_pt[2],0)   RCMHiggs_jet2_pt              RCMHiggs_jet2_pt              RCMHiggs_jet2_pt                                                'F'    [0,1047.00219727]
Alt$(RCMV_jets_pt[0],0)       RCMV_jet0_pt                  RCMV_jet0_pt                  RCMV_jet0_pt                                                    'F'    [0,2650.16699219]
Alt$(RCMV_jets_pt[1],0)       RCMV_jet1_pt                  RCMV_jet1_pt                  RCMV_jet1_pt                                                    'F'    [0,1448.52954102]
Alt$(RCMV_jets_pt[2],0)       RCMV_jet2_pt                  RCMV_jet2_pt                  RCMV_jet2_pt                                                    'F'    [0,952.958618164]
Alt$(RCMTop_jets_eta[0],-10)  RCMTop_jet0_eta               RCMTop_jet0_eta               RCMTop_jet0_eta                                                 'F'    [-10,1.9987705946]
Alt$(RCMTop_jets_eta[1],-10)  RCMTop_jet1_eta               RCMTop_jet1_eta               RCMTop_jet1_eta                                                 'F'    [-10,1.99992537498]
Alt$(RCMTop_jets_eta[2],-10)  RCMTop_jet2_eta               RCMTop_jet2_eta               RCMTop_jet2_eta                                                 'F'    [-10,1.99736762047]
Alt$(RCMHiggs_jets_eta[0],-10) RCMHiggs_jet0_eta              RCMHiggs_jet0_eta              RCMHiggs_jet0_eta                                                 'F'    [-10,1.99995565414]
Alt$(RCMHiggs_jets_eta[1],-10) RCMHiggs_jet1_eta              RCMHiggs_jet1_eta              RCMHiggs_jet1_eta                                                 'F'    [-10,1.99989056587]
Alt$(RCMHiggs_jets_eta[2],-10) RCMHiggs_jet2_eta              RCMHiggs_jet2_eta              RCMHiggs_jet2_eta                                                 'F'    [-10,1.97164785862]
Alt$(RCMV_jets_eta[1],-10)    RCMV_jet1_eta                 RCMV_jet1_eta                 RCMV_jet1_eta                                                   'F'    [-10,1.99237644672]
Alt$(RCMV_jets_eta[2],-10)    RCMV_jet2_eta                 RCMV_jet2_eta                 RCMV_jet2_eta                                                   'F'    [-10,1.81877052784]
Alt$(RCMTop_jets_consts_n[0],0) RCMTop_jet0_nconsts             RCMTop_jet0_nconsts             RCMTop_jet0_nconsts                                                 'F'    [0,8]
Alt$(RCMTop_jets_consts_n[1],0) RCMTop_jet1_nconsts             RCMTop_jet1_nconsts             RCMTop_jet1_nconsts                                                 'F'    [0,7]
Alt$(RCMTop_jets_consts_n[2],0) RCMTop_jet2_nconsts             RCMTop_jet2_nconsts             RCMTop_jet2_nconsts                                                 'F'    [0,6]
Alt$(RCMHiggs_jets_consts_n[1],0) RCMHiggs_jet1_nconsts             RCMHiggs_jet1_nconsts             RCMHiggs_jet1_nconsts                                                   'F'    [0,2]
Alt$(RCMHiggs_jets_consts_n[2],0) RCMHiggs_jet2_nconsts             RCMHiggs_jet2_nconsts             RCMHiggs_jet2_nconsts                                                   'F'    [0,2]
Alt$(RCMV_jets_consts_n[0],0) RCMV_jet0_nconsts             RCMV_jet0_nconsts             RCMV_jet0_nconsts                                               'F'    [0,2]
Alt$(RCMV_jets_consts_n[1],0) RCMV_jet1_nconsts             RCMV_jet1_nconsts             RCMV_jet1_nconsts                                               'F'    [0,2]
Alt$(RCMV_jets_consts_n[2],0) RCMV_jet2_nconsts             RCMV_jet2_nconsts             RCMV_jet2_nconsts                                               'F'    [0,2]
Alt$(RCMTop_jets_bconsts_n[0],0) RCMTop_jet0_nbconsts             RCMTop_jet0_nbconsts             RCMTop_jet0_nbconsts                                                  'F'    [0,4]
Alt$(RCMTop_jets_bconsts_n[1],0) RCMTop_jet1_nbconsts             RCMTop_jet1_nbconsts             RCMTop_jet1_nbconsts                                                  'F'    [0,4]
Alt$(RCMTop_jets_bconsts_n[2],0) RCMTop_jet2_nbconsts             RCMTop_jet2_nbconsts             RCMTop_jet2_nbconsts                                                  'F'    [0,4]
Alt$(RCMHiggs_jets_bconsts_n[1],0) RCMHiggs_jet1_nbconsts             RCMHiggs_jet1_nbconsts             RCMHiggs_jet1_nbconsts                                                    'F'    [0,4]
Alt$(RCMHiggs_jets_bconsts_n[2],0) RCMHiggs_jet2_nbconsts             RCMHiggs_jet2_nbconsts             RCMHiggs_jet2_nbconsts                                                    'F'    [0,3]
Alt$(RCMV_jets_bconsts_n[1],0) RCMV_jet1_nbconsts             RCMV_jet1_nbconsts             RCMV_jet1_nbconsts                                                'F'    [0,4]
Alt$(RCMV_jets_bconsts_n[2],0) RCMV_jet2_nbconsts             RCMV_jet2_nbconsts             RCMV_jet2_nbconsts                                                'F'    [0,3]
el1_pt+mu1_pt                 lep_pt                        lep_pt                        lep_pt                                                          'F'    [30.0034389496,1410.32543945]
ptw                           ptw                           ptw                           ptw                                                             'F'    [0.815694749355,1879.80224609]
jets_n                        jets_n                        jets_n                        jets_n                                                          'F'    [6,17]
RCTTMass_jets_n               RCTTMass_jets_n               RCTTMass_jets_n               RCTTMass_jets_n                                                 'F'    [2,6]
RCMTop_jets_n                 RCMTop_jets_n                 RCMTop_jets_n                 RCMTop_jets_n                                                   'F'    [0,5]
RCMHiggs_jets_n               RCMHiggs_jets_n               RCMHiggs_jets_n               RCMHiggs_jets_n                                                 'F'    [0,4]
RCMV_jets_n                   RCMV_jets_n                   RCMV_jets_n                   RCMV_jets_n                                                     'F'    [0,4]
Alt$(m_vlq_rcjets_drmax[0],0) mvlq_rc1                      mvlq_rc1                      mvlq_rc1                                                        'F'    [-865.787780762,6603.37011719]
VLQtype                       VLQtype                       VLQtype                       VLQtype                                                         'F'    [1,3]
sampleID                      sampleID                      sampleID                      sampleID                                                        'F'    [302480,407344]
sampleName                    sampleName                    sampleName                    sampleName                                                      'F'    [3,17]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 26 )
   {
      // the training input variables
      const char* inputVars[] = { "meff", "leadingdEta_RCjets", "leadingdR_RCjets", "leadingdR_RCTTMassRCTTMass", "dEtamin_RCTTMassRCTTMass", "dRmin_RCTTMassRCTTMass", "dPhiaverage_RCjets", "dRaverage_RCjets", "Alt$(RCjets_pt[1],0)", "Alt$(RCjets_pt[2],0)", "Alt$(RCMTop_jets_pt[0],0)", "Alt$(RCMHiggs_jets_pt[0],0)", "Alt$(RCMHiggs_jets_pt[1],0)", "Alt$(RCMV_jets_eta[0],-10)", "Alt$(RCMHiggs_jets_consts_n[0],0)", "Alt$(RCMHiggs_jets_bconsts_n[0],0)", "Alt$(RCMV_jets_bconsts_n[0],0)", "leptop_pt", "mtw", "residualMET_Pt", "met", "mT_bmin", "trkbjets_n", "Alt$(m_vlq_rcttmass_drmax[0],0)", "Alt$(m_vlq_rcttmass_drmax[1],0)", "Alt$(m_vlq_rcjets_drmax[1],0)" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'I';
      fType[15] = 'I';
      fType[16] = 'I';
      fType[17] = 'D';
      fType[18] = 'D';
      fType[19] = 'D';
      fType[20] = 'D';
      fType[21] = 'D';
      fType[22] = 'I';
      fType[23] = 'D';
      fType[24] = 'D';
      fType[25] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[26];
   double fVmax[26];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[26];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
            retval = GetMvaValue__( inputValues );
      }

      return retval;
   }
